### ISSUE TITLE
PanicExecption in python sdk

### ISSUE THREAD

**Issue by cody-scott** [bitwarden/sdk#697]
### Steps To Reproduce

when attempting to create the api twice in the same process, getting an error.

```python

from bitwarden_sdk import BitwardenClient
client = BitwardenClient()

client = BitwardenClient()
```

raises

```python
File c:\Users\username\Miniconda3\envs\jupyer_11\Lib\site-packages\bitwarden_sdk\bitwarden_client.py:10, in BitwardenClient.__init__(self, settings)
      8 def __init__(self, settings: ClientSettings = None):
      9     if settings is None:
---> 10         self.inner = bitwarden_py.BitwardenClient(None)
     11     else:
     12         settings_json = json.dumps(settings.to_dict())

PanicException: called `Result::unwrap()` on an `Err` value: SetLoggerError(())
```

### Expected Result

Not raise an error, or return a reference to the existing object

### Actual Result

Panic error raised.

```python
File c:\Users\username\Miniconda3\envs\jupyer_11\Lib\site-packages\bitwarden_sdk\bitwarden_client.py:10, in BitwardenClient.__init__(self, settings)
      8 def __init__(self, settings: ClientSettings = None):
      9     if settings is None:
---> 10         self.inner = bitwarden_py.BitwardenClient(None)
     11     else:
     12         settings_json = json.dumps(settings.to_dict())

PanicException: called `Result::unwrap()` on an `Err` value: SetLoggerError(())
```

### Additional Context

Ideally it would either create a new instance of the object, or return a reference to the existing object instead of the panic error.

The (likely) preferred approach should be to create the variable once and pass it around, but ideally i should be able to create a second reference to the object and use it the same as the first, or this would be documented if its not the anticipated behaviour.

I can't run this in a jupyter notebook as well without calling the BW client at the top scope either, otherwise subsequent calls raises the error.

### Operating System

Windows

### Operating System Version

10

### Build Version

0.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Resolved by https://github.com/bitwarden/sdk/pull/676

**Comment by mittkkoo** [comment]
Maybe I didn't compile correctly the fix or the fix doesn't help.
This is what I tried:
https://github.com/bitwarden/sdk/pull/676#issuecomment-2072997679
I did `cargo build` in crates/bws as in the newest state of the main branch and then `cargo install --path .`, but what next? The lookup plugin still fails with a panic error as before.
